### ISSUE TITLE
Feature idea: use IP Geolocation to determine region and expose region to /client/servers

### ISSUE THREAD

**Issue by laundmo** [R2Northstar/NorthstarMasterServer#15]
This would allow for adding a region filter or sort to the server browser.

Advantages:
- Make server names more readable since they don't have to include [EU] or [NA West]
- Make it easier to find low-ping servers

Disadvantages:
- Geolocation lookup needed on masterserver, either through API or a downloadable database like <https://db-ip.com/db/> or <https://www.maxmind.com/en/geoip2-country-database>

Im willing to PR this, but would like to have some discussion about this first.

**Comment by pg9182** [comment]
duplicate of R2Northstar/Northstar#41

**Comment by laundmo** [comment]
closed as duplicate
