### ISSUE TITLE
Registered ID's for uniquely identifying servers.

### ISSUE THREAD

**Issue by emma-miler** [R2Northstar/NorthstarMasterServer#26]
It would be nice if server owners could register a unique server id for each game server they want to host.
This way an individual server, eg: `laundmo's fastball randomiser`, could be uniquely identified between restarts, allowing for stuff like favoriting servers.
I'm not exactly sure yet what would be the best way of registering and authenticating these servers, but perhaps a short key pair between game and master servers would suffice.

**Comment by barnabwhy** [comment]
Relates to #41

**Comment by abarichello** [comment]
Closed by https://github.com/R2Northstar/NorthstarMasterServer/pull/41
