### ISSUE TITLE
Add support to frp

### ISSUE THREAD

**Issue by PencilCore** [R2Northstar/NorthstarMasterServer#92]
I'm recently hosting a server through frp, I've also followed the instructions in the wiki. And I found it's workable using frp to connect to the server through 37015 port, but I can't find it when I tried to find my server in the serverlist. There's a problem to combine the 8081 port and the 37015 port together. And the connection quality is around 60-80 ping (three provinces away)
I'm hosting a server using r2northstarcn, I guess they're the same huh.

**Comment by PencilCore** [comment]
Tried ns_server_bind_address to 37015 address, didn't work, because frp only creates separate address for each port, one solution is to add ns_server_verify_port_address or something? I don't know, it's not a urgent issue, just allow to host servers more easily.

**Comment by GeckoEidechse** [comment]
Uh, you might wanna explain or link to what "frp" is ^^

Never heard about it before, I assume this? https://github.com/fatedier/frp

Also this repo is about the MasterServer (i.e. https://northstar.tf) not the gameserver you actually connect to when you join a server in Northstar.

So unless this is actually about the MasterServer, https://github.com/R2Northstar/NorthstarLauncher is the way to go ^^

**Comment by PencilCore** [comment]
Yeah this

**Comment by pg9182** [comment]
They're asking about changing the IP address used for server registration.

@PencilCore, you'll need to proxy outgoing HTTP via your frp server.
